addon/index.js, package.json
=> Minor fixes

README.md, addon/utils/prop-types.js
=> Add null propType

README.md, addon/utils/prop-types.js
=> Add instanceOf propType

README.md, addon/utils/prop-types.js
It uses `Ember.get`, so it should work for both Ember.Objects and POJOs.
#MINOR#
=> Add shape propType

package.json
#MINOR#
* **Changed** from `ember-lodash` to `ember-lodash-shim`.
=> Switch to ember-lodash-shim

package.json, tests/unit/index-test.js, tests/unit/mixins/prop-types-test.js, tests/unit/prop-types/array-test.js, tests/unit/prop-types/bool-test.js, tests/unit/prop-types/ember-object-test.js, tests/unit/prop-types/func-test.js, tests/unit/prop-types/null-test.js, tests/unit/prop-types/number-test.js, tests/unit/prop-types/object-test.js, tests/unit/prop-types/string-test.js
#PATCH#
* **Added** a bunch of tests to help prevent future regressions and verify addon does what it advertises.
=> Add a bunch of tests

addon/utils/prop-types.js, tests/unit/prop-types/shape-test.js
#PATCH#
* **Added** tests for `shape` prop-type and commented out tests that exercise issue #24.
=> Add shape tests

addon/utils/prop-types.js, tests/unit/prop-types/instance-of-test.js
#PATCH#
* **Added** tests for `instanceOf` prop-type.
=> Add tests for instanceOf

tests/unit/prop-types/one-of-type-test.js
#PATCH#
<br />
<br /># CHANGELOG
<br />
<br />* **Added** tests for `oneOfType` prop-type.
=> Add oneOfType tests

addon/utils/prop-types.js, tests/unit/prop-types/one-of-test.js
#PATCH#
* **Added** tests for `oneOf` prop-type.
=> Add oneOf tests

addon/utils/prop-types.js, addon/utils/validators/array.js, addon/utils/validators/bool.js, addon/utils/validators/ember-object.js, addon/utils/validators/func.js, addon/utils/validators/index.js, addon/utils/validators/instance-of.js, addon/utils/validators/null.js, addon/utils/validators/number.js, addon/utils/validators/object.js, addon/utils/validators/one-of-type.js, addon/utils/validators/one-of.js, addon/utils/validators/shape.js, addon/utils/validators/string.js
#PATCH#
* Split source code up into separate modules as a first step in refactoring and improving implementation.
=> Refactor source into separate modules

addon/utils/prop-types.js, addon/utils/validators/array-of.js, addon/utils/validators/index.js, tests/unit/prop-types/array-of-test.js
#MINOR#
* **Added** `arrayOf` prop-type.
=> Add arrayOf prop-type

addon/utils/prop-types.js, addon/utils/validators/any.js, addon/utils/validators/index.js, tests/unit/prop-types/any-test.js
#MINOR#
* **Added** `any` prop-type.
=> Add any prop-type to resolve #31

addon/utils/prop-types.js, addon/utils/validators/index.js, addon/utils/validators/symbol.js, index.js, tests/unit/prop-types/symbol-test.js
#PATCH#
* **Added** `symbol` prop-type.
=> Add symbol prop-type to resolve #29

addon/utils/prop-types.js, addon/utils/validators/element.js, addon/utils/validators/index.js, tests/unit/prop-types/element-test.js
#MINOR#
* **Added** `element` prop-type.
=> Add element prop-type to resolve #30

README.md, package.json
#PATCH#
* **Addedd** missing prop-types to README.
* **Upgraded** `ember-get-config` to latest version.
=> Update README and ember-get-config to latest version

package.json
#PATCH#
* Addressed the following security vulnerability: https://nodesecurity.io/advisories/118.
=> Patch security vulnerability

README.md, package.json
#PATCH#
* Cleaned up README to pass default config for remark-lint and better organized badges.
* Updated dev dependencies.
=> README cleanup

.travis.yml
#PATCH#
* Updated CI configuration to not run npm scripts on install.
=> Don't run npm scripts on install

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
#PATCH#
* **Added** pull request template.
=> Add pull request template

addon/mixins/prop-types.js, tests/unit/mixins/prop-types-test.js
Resolves #63 
* Support cases where components and mixins both use this mixin.
=> Support mixins

tests/dummy/config/environment.js
* Attempt to fix publishing of dummy app to `gh-pages` branch.
=> Switch to hash locationType in hopes of fixing demo app

.github/PULL_REQUEST_TEMPLATE.md, .npmignore, .travis.yml, .travis/publish-coverage.sh, ember-cli-build.js, package.json
=> Work with latest pr-bumper

README.md
Added link to React's type-checking documentation in README
=> Link to React docs

addon/utils/validators/array-of.js, addon/utils/validators/array.js, addon/utils/validators/bool.js, addon/utils/validators/element.js, addon/utils/validators/ember-component.js, addon/utils/validators/ember-object.js, addon/utils/validators/func.js, addon/utils/validators/instance-of.js, addon/utils/validators/null.js, addon/utils/validators/number.js, addon/utils/validators/object.js, addon/utils/validators/one-of-type.js, addon/utils/validators/shape.js, addon/utils/validators/string.js, addon/utils/validators/symbol.js, package.json, tests/dummy/app/fixtures/contributors.js, tests/helpers/validator.js, tests/unit/prop-types/hash-api/array-of-test.js, tests/unit/prop-types/hash-api/one-of-type-test.js, tests/unit/prop-types/hash-api/shape-test.js, tests/unit/prop-types/property-api/array-of-test.js, tests/unit/prop-types/property-api/one-of-type-test.js, tests/unit/prop-types/property-api/shape-test.js
- Log typeOf value when asserting type
=> feat(validators): Update validators to log typeof value provided

addon/utils/prop-types.js, addon/utils/validators/date.js, addon/utils/validators/index.js, tests/dummy/app/fixtures/validators.js, tests/unit/prop-types/hash-api/date-test.js, tests/unit/prop-types/property-api/date-test.js
=> Added date type

.travis.yml, tests/dummy/app/templates/application.hbs
=> Fix HTMLBars linting

package.json
* **Upgrade** `ember-get-config`
=> Upgrade `ember-get-config`

README.md, addon/utils/prop-types.js, addon/utils/validators/index.js, addon/utils/validators/regexp.js, tests/dummy/app/fixtures/validators.js, tests/unit/prop-types/hash-api/regexp-test.js, tests/unit/prop-types/property-api/regexp-test.js
=> Add regexp type

package.json
* Update `ember-spread` devDependency to ^4.0.1
=> Update ember-spread devDependency to ^4.0.1

package-lock.json, package.json
No PR should be opened without opening an issue first.  Any change needs to be discussed before proceeding.
Provide a general summary of the issue addressed in the title above
Which issue(s) does this PR address?
Put `Closes #XXXX` below to auto-close the issue that this PR addresses:
* Closes #
Please provide screenshots or recordings if this PR is modifying the visual UI or UX.
**This project uses [semver](http://semver.org), please check the scope of this PR:**
Examples:
* **NONE**
* _README.md_ changes
* test additions
* changes to files that are not used by a consuming application (_.travis.yml_, _.gitignore_, etc)
* **PATCH**
* backwards-compatible bug fix
* nothing about how to use the code has changed
* nothing about the outcome of the code has changed (though it likely corrected …
=> Update ember-spread devDependency to ^5.0.0

.travis/maybe-bump-version.sh, .travis/maybe-publish-coverage.sh, .travis/maybe-publish-gh-pages.sh
No PR should be opened without opening an issue first.  Any change needs to be discussed before proceeding.
Provide a general summary of the issue addressed in the title above
Which issue(s) does this PR address?
Put `Closes #XXXX` below to auto-close the issue that this PR addresses:
* Closes #
Please provide screenshots or recordings if this PR is modifying the visual UI or UX.
**This project uses [semver](http://semver.org), please check the scope of this PR:**
Examples:
* **NONE**
* _README.md_ changes
* test additions
* changes to files that are not used by a consuming application (_.travis.yml_, _.gitignore_, etc)
* **PATCH**
* backwards-compatible bug fix
* nothing about how to use the code has changed
* nothing about the outcome of the code has changed (though it likely corrected …
=> Update .travis/ scripts

.travis.yml
No PR should be opened without opening an issue first.  Any change needs to be discussed before proceeding.
Provide a general summary of the issue addressed in the title above
Which issue(s) does this PR address?
Put `Closes #XXXX` below to auto-close the issue that this PR addresses:
* Closes #
Please provide screenshots or recordings if this PR is modifying the visual UI or UX.
**This project uses [semver](http://semver.org), please check the scope of this PR:**
Examples:
* **NONE**
* _README.md_ changes
* test additions
* changes to files that are not used by a consuming application (_.travis.yml_, _.gitignore_, etc)
* **PATCH**
* backwards-compatible bug fix
* nothing about how to use the code has changed
* nothing about the outcome of the code has changed (though it likely corrected …
=> Update travis.yml with build variable and remove node stable build

addon/extensions/component-prop-types.js, addon/mixins/prop-types.js
#MAJOR#
* Run es5 getter codemod
=> Run es5 getter codemod

package-lock.json, package.json
#patch#
* Remove ember-string-ishtmlsafe-polyfill dependency
=> Remove ember-string-ishtmlsafe-polyfill dependency
