README.md, addon/extensions/component-prop-types.js, addon/initializers/component-prop-types.js, app/initializers/component-prop-types.js, package.json, tests/unit/initializers/component-prop-types-test.js
#MINOR#
Updated this add-on so that it is no longer necessary to add this mixin to the Component explicitly. The usage for components can now be:
```
import Ember from 'ember'
import {PropTypes} from 'ember-prop-types'
export default Ember.Component.extend({
propTypes: {
foo: PropTypes.string,
bar: PropTypes.number.isRequired,
baz: PropTypes.oneOf([
PropTypes.bool,
PropTypes.string
])
},
getDefaultProps () {
return {
foo: 'This is going to be highly profitable'
}
}
})
```
=> Component extention

README.md, addon/utils/prop-types.js
This API is more consistent with React
#MAJOR#
Resolves #10
=> Rename `oneOf` to `oneOfType` and implement `oneOf`

addon/mixins/prop-types.js, addon/utils/prop-types.js, package.json
#feature#
- Removed lodash as a dependency to avoid lodash as a downstream requirement
- Replaced lodash functions with equivalent Ember/ES6/custom functions
=> Removing lodash as a dependency

addon/utils/validators/index.js
#PATCH#
Fixes https://github.com/ciena-blueplanet/ember-prop-types/issues/47
* **Fixed** issue when `Ember.assign` does not exist to fallback on `Object.assign` then `Ember.merge`.
=> Use Object.assign if no Ember.assign. And Ember.merge if no Object.assign

ember-cli-build.js, index.js
#PATCH#
All tests pass locally without this. Would love to not include the polyfill if possible.
* Only import polyfill for CI and not for consuming apps. Apps that want Symbol can pay as they go.
=> remove polyfill

package.json
#PATCH#
* **Addedd** `npm-install-security-check` as a dependency to make consumers more security conscious.
=> Add npm-install-security-check

addon/utils/validators/array-of.js, tests/helpers/validator.js, tests/unit/prop-types/array-of-test.js
* **Fixed** a bug in the `PropTypes.arrayOf` validator when used in conjunction with the `PropTypes.shape` validator.
=> Fix bug in array-of when used with shape

addon/utils/validators/array-of.js, addon/utils/validators/shape.js, tests/unit/prop-types/array-of-test.js, tests/unit/prop-types/shape-test.js
* **Added** more detailed messaging for sub-property validations when using `PropTypes.arrayOf` or `PropTypes.shape`
=> More detailed msgs for PropTypes.{shape,arrayOf)

addon/mixins/prop-types.js, tests/unit/mixins/prop-types-test.js
* **Fixed** bug where defaults weren't being applied when consumer passes in `undefined` for a property with defaults.
=> Apply defaults when passed in value is undefined

.eslintrc, addon/extensions/component-prop-types.js, addon/mixins/prop-types.js, addon/utils/validators/index.js, addon/utils/validators/shape.js, app/initializers/component-prop-types.js, package.json, tests/dummy/app/app.js, tests/dummy/app/router.js, tests/dummy/app/routes/application.js, tests/dummy/config/environment.js, tests/helpers/destroy-app.js, tests/helpers/resolver.js, tests/helpers/start-app.js, tests/test-helper.js, tests/unit/mixins/prop-types-test.js, tests/unit/prop-types/any-test.js, tests/unit/prop-types/array-of-test.js, tests/unit/prop-types/array-test.js, tests/unit/prop-types/bool-test.js, tests/unit/prop-types/element-test.js, tests/unit/prop-types/null-test.js, tests/unit/prop-types/number-test.js, tests/unit/prop-types/object-test.js, tests/unit/prop-types/string-test.js, tests/unit/prop-types/symbol-test.js
* **Added** opt-in validation checks when properties that are spec'd in `propTypes` are updated. To enable this feature simply add the following to `config/environment.js`:
```js
'ember-prop-types': {
validateOnUpdate: true
}
```
=> Validate spec'd properties on update

addon/mixins/prop-types.js, package.json, tests/dummy/app/routes/application.js, tests/dummy/app/templates/application.hbs, tests/dummy/config/environment.js, tests/unit/prop-types/bool-test.js
* **Added** ability to validate properties on initialized that are nested under a single property via something like [ember-spread](https://github.com/ciena-blueplanet/ember-spread).
=> Support spread property on initial validation

addon/mixins/prop-types.js, addon/utils/logger.js, tests/dummy/app/routes/application.js, tests/dummy/app/templates/application.hbs, tests/helpers/validator.js, tests/unit/mixins/prop-types-test.js
Resolves #90
* **Added** the ability to enable/disable validation from an environment configuration setting, allowing consumers to control which environments `ember-prop-types` warnings/errors appear in. Below is an example of how to explicitly enable validation:
```js
'ember-prop-types': {
validate: true
}
```
> Note: Without explicitly adding this setting things will continue to work as they did before in which validation is enabled for all environments except *production*.
* **Fixed** validation error messages when `throwErrors` is set to true to match error messages when errors are not thrown (logging warnings instead).
=> Allow validation to be disabled/enabled via setting

addon/utils/prop-types.js, addon/utils/validators/ember-component.js, addon/utils/validators/index.js, ember-cli-build.js, tests/dummy/app/fixtures/validators.js, tests/dummy/app/templates/application.hbs, tests/unit/prop-types/hash-api/ember-component-test.js, tests/unit/prop-types/property-api/ember-component-test.js
Resolves #100 
* **Added** `EmberComponent` prop-type for properties that come from the `{{component}}` helper.
=> Add EmberComponent type

addon/mixins/prop-types.js, addon/utils/prop-types.js, tests/dummy/app/fixtures/validators.js, tests/helpers/validator.js, tests/index.html, tests/unit/prop-types/hash-api/any-test.js, tests/unit/prop-types/hash-api/array-of-test.js, tests/unit/prop-types/hash-api/array-test.js, tests/unit/prop-types/hash-api/bool-test.js, tests/unit/prop-types/hash-api/element-test.js, tests/unit/prop-types/hash-api/ember-component-test.js, tests/unit/prop-types/hash-api/ember-object-test.js, tests/unit/prop-types/hash-api/func-test.js, tests/unit/prop-types/hash-api/instance-of-test.js, tests/unit/prop-types/hash-api/null-test.js, tests/unit/prop-types/hash-api/number-test.js, tests/unit/prop-types/hash-api/object-test.js, tests/unit/prop-types/hash-api/one-of-test.js, tests/unit/prop-types/hash-api/one-of-type-test.js, tests/unit/prop-types/hash-api/shape-test.js, tests/unit/prop-types/hash-api/string-test.js, tests/unit/prop-types/hash-api/symbol-test.js
Resolves #82
* **Added** new `updatable` option to all types to flag components that shouldn't allow updates. By default all properties will allow updates so specifying `updatable: true` isn't necessary.
=> Add updatable option

.travis.yml, bower.json, config/ember-try.js, package.json
* **Upgraded** to test against Ember 2.11.
=> Upgrade to Ember 2.11

addon/utils/validators/ember-component.js
* **Fixed** `EmberComponent` prop type to work properly with Glimmer 2.
=> Fix EmberComponent prop type for Ember 2.11

README.md
I almost completely missed that the docs site existed 😃 
- Added link to own docs page
=> link to own docs page

.gitignore, addon/mixins/prop-types.js, package.json
#118 broke the hierarchy of getDefaultProps - previously parent layers properties were accessible to the children.  Also made the application of the hierarchy more robust by allowing children to override parent defaults while not overriding properties set explicitly on the target.
- Fixed a regression in the execution order of getDefaultProps introduced in #118
=> Fixing a regression in getDefaultProps execution ordering

addon/utils/validators/instance-of.js
fixed error with nameOfType if typedef does not return a function string
=> fixed error with nameOfType.  typedef may not return a function string.

addon/utils/validators/ember-component.js
* Fix ember-component validator usage in `ember#lts-2-8` branch of Ember
=> Closes ciena-blueplanet/ember-prop-types#136

addon/utils/validators/string.js, tests/unit/prop-types/hash-api/string-test.js, tests/unit/prop-types/property-api/string-test.js
Update string validation to support Ember SafeString objects. Fixes #128.
=> Update string validation to support Ember SafeString objects.

bower.json, package.json
* Install `ember-string-ishtmlsafe-polyfill` to address #139
=> Closes ciena-blueplanet/ember-prop-types#139

addon/mixins/prop-types.js, addon/utils/validators/index.js
New version of #142, more or less.
- Adds a fallback for Object.assign for browsers that don't support it (i.e. IE).
=> Object.assign fallback (v2)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, .pr-bumper.json, .travis.yml, .travis/maybe-bump-version.sh, .travis/maybe-publish-coverage.sh, package-lock.json, package.json
Closes: https://agile-jira.ciena.com/browse/FROST-1281 and https://agile-jira.ciena.com/browse/FROST-1320
* **Updated** pull request template
* **Added** issue template
* **Updated** to `pr-bumper` version `3`
* **Updated** to node 8
* **Added** slack integration
* **Updated** `ember-frost-test` to `^4.0.1`
* **Updated** `ember-test-utils` to `^8.1.1`
* **Updated** `ember-cli-frost-blueprints` to `^5.0.2`
* **Added** `package-lock.json` file
=> Update templates and integrate with slack

addon/utils/validators/ember-component.js
No, encountered while validating upgrade path for Frost Foundation to Ember CLI 3.x
The key that we are looking at to validate that an object is an Ember component has changed sometime between Ember CLI 2.12.3 and Ember CLI 3.2.0
n/a
n/a
**This project uses [semver](http://semver.org), please check the scope of this PR:**
Examples:
* **NONE**
* _README.md_ changes
* test additions
* changes to files that are not used by a consuming application (_.travis.yml_, _.gitignore_, etc)
* **PATCH**
* backwards-compatible bug fix
* nothing about how to use the code has changed
* nothing about the outcome of the code has changed (though it likely corrected it)
* changes to demo app (_/tests/dummy/_)
* **MINOR**
* adding functionality in a backwards-compatible manner
* nothing about how used to use …
=> Update ember-component validator to work with Ember CLI 3.2.0
